# This is a basic workflow to help you get started with Actions

name: upload to oss

# Controls when the action will run. Triggers the workflow on push aor pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  #pull_request:
   # branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          # endpoint 可以去oss控制台上查看
          endpoint: "oss-cn-beijing.aliyuncs.com"
          # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      # setup node env
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"  
      - run: |
          yarn install 
          yarn build
      - run: ossutil cp dist oss://oomall-micro-privilege-application/ -rf
